exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "legacy",
]
line-length = 120
target-version = "py310"

[per-file-ignores]
"__init__.py" = ["F401"]
