name: egame-179
channels:
- conda-forge
dependencies:
- python>=3.10
- aiomysql
- alembic
- antlr4-python3-runtime
- blas=*=mkl
- bs4
- fastapi
- httptools
- httpx
- icecream
- jupyterlab
- mypy
- mypy_extensions
- mysqlclient
- numpy
- omegaconf
- pandas
- prettytable
- pyarrow
- python-dotenv
- pytest
- pytest-asyncio
- pytest-cov
- pytest-env
- pytest-mypy
- simplejson
- sqlalchemy
- sqlmodel
- streamlit
- tqdm
- ujson
- uvicorn
- yarl
