name: egame179
channels:
- conda-forge
- defaults
dependencies:
- python>=3.10
- aiomysql
- alembic
- blas=*=mkl
- bs4
- fastapi
- httptools
- httpx
- icecream
- jupyterlab
- libblas=*=*mkl
- mypy
- mypy_extensions
- mysqlclient
- numpy
- omegaconf
- pandas
- pyarrow
- python-dotenv
- pytest
- pytest-asyncio
- pytest-cov
- pytest-env
- pytest-mypy
- sqlalchemy
- sqlmodel
- streamlit
- tqdm
- ujson
- uvicorn
- yarl
