name: egame-179
channels:
- conda-forge
dependencies:
- python>=3.10
- aiomysql
- alembic
- antlr4-python3-runtime
- bs4
- fastapi
- httptools
- httpx
- mysqlclient
- networkx
- numpy
- omegaconf
- pandas
- prettytable
- pyarrow
- python-dotenv
- simplejson
- seaborn
- sqlalchemy
- sqlmodel
- streamlit
- tqdm
- ujson
- uvicorn
- yarl
# dev packages
- icecream
- ipywidgets
- jupyterlab
- mypy
- mypy_extensions
- pytest
- pytest-asyncio
- pytest-cov
- pytest-env
- pytest-mypy
- types-ujson
