"""Created all necessary tables.

Revision ID: 2b7380507a71
Revises: 819cbf6e030b
Create Date: 2022-09-03 12:30:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b7380507a71"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("login", sa.String(length=20), nullable=True),
        sa.Column("password", sa.String(length=20), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
